# Generated by Django 5.2 on 2025-04-23 01:38

import autoslug.fields
import blog.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="title",
                        slugify=blog.models.custom_slugify,
                        unique=True,
                        verbose_name="URL别名",
                    ),
                ),
                (
                    "date_published",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="发布日期"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
            ],
            options={
                "ordering": ["-date_published"],
            },
        ),
        migrations.CreateModel(
            name="FriendLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.URLField(blank=True, null=True, verbose_name="头像链接")),
                ("name", models.CharField(max_length=100, verbose_name="昵称")),
                ("url", models.URLField(verbose_name="链接地址")),
                (
                    "site_description",
                    models.TextField(blank=True, null=True, verbose_name="站点描述"),
                ),
                (
                    "my_description",
                    models.TextField(blank=True, null=True, verbose_name="我的介绍"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
            ],
        ),
    ]
