# Generated by Django 5.2 on 2025-05-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_category_blogarticle_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogarticle",
            name="excerpt",
            field=models.TextField(blank=True, null=True, verbose_name="摘要"),
        ),
    ]
