# Generated by Django 5.2 on 2026-06-11 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blogarticle_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_tech",
            field=models.BooleanField(default=True, verbose_name="技术类"),
        ),
        migrations.AlterField(
            model_name="blogarticle",
            name="date_published",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="发布日期"
            ),
        ),
    ]
